# Generated by Django 3.1.1 on 2020-09-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('name', models.CharField(choices=[('spring', 'spring'), ('summer', 'summer'), ('fall', 'fall'), ('winter', 'winter')], max_length=255, unique=True)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('fruit', 'fruit'), ('vegetable', 'vegetable')], max_length=255)),
                ('seasons', models.ManyToManyField(to='seasonal.Season')),
            ],
        ),
    ]
