# Generated by Django 3.1.1 on 2020-09-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='sub_names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
